### ISSUE TITLE
`plugin "loki" not found` error

### ISSUE THREAD

**Issue by 3howley** [ericvolp12/bsky-experiments#1]
When trying to build the container, I received the following error:

```
Error response from daemon: error looking up logging plugin loki: plugin "loki" not found
```

After doing [some research](https://docs.obol.tech/docs/int/faq/errors#loki-plugin-not-found-error), I found a fix:

```
$ docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
```

**Comment by ericvolp12** [comment]
This should be fixed by removing the `logging:` block from the docker compose YAML. I'm using loki as my logging driver but you don't have to.
